# coding=utf-8
import logging
import os
import sys
from dataclasses import dataclass, field
from typing import Optional
from flask import Flask, request, jsonify, abort
import numpy as np
from datasets import ClassLabel, load_dataset, Dataset
from seqeval.metrics import accuracy_score, f1_score, precision_score, recall_score

import transformers
from transformers import (
    AutoConfig,
    AutoModelForTokenClassification,
    AutoTokenizer,
    DataCollatorForTokenClassification,
    HfArgumentParser,
    PreTrainedTokenizerFast,
    Trainer,
    TrainingArguments,
    set_seed,
)
from transformers.trainer_utils import is_main_process

app = Flask(__name__)
logger = logging.getLogger(__name__)


@dataclass
class ModelArguments:
    """
    Arguments pertaining to which model/config/tokenizer we are going to fine-tune from.

     --output_dir cosmetic_ner --do_predict --max_length 64

    """

    model_name_or_path: str = field(
        default="cosmetic_ner",metadata={"help": "Path to pretrained model or model identifier from huggingface.co/models"}
    )
    config_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained config name or path if not the same as model_name"}
    )
    tokenizer_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained tokenizer name or path if not the same as model_name"}
    )
    cache_dir: Optional[str] = field(
        default=None,
        metadata={"help": "Where do you want to store the pretrained models downloaded from huggingface.co"},
    )


@dataclass
class DataTrainingArguments:
    """
    Arguments pertaining to what data we are going to input our model for training and eval.
    """

    task_name: Optional[str] = field(default="ner", metadata={"help": "The name of the task (ner, pos...)."})
    dataset_name: Optional[str] = field(
        default=None, metadata={"help": "The name of the dataset to use (via the datasets library)."}
    )
    script_file: Optional[str] = field(
        default='data/cosmetic_ner.py', metadata={"help": "处理数据集的文件路径"}
    )
    dataset_config_name: Optional[str] = field(
        default='CosmeticsNerConfig', metadata={"help": "The configuration name of the dataset to use (via the datasets library)."}
    )
    train_file: Optional[str] = field(
        default='dataset/cosmetic/train.txt', metadata={"help": "The input training data file (a csv or JSON file)."}
    )
    validation_file: Optional[str] = field(
        default='dataset/cosmetic/dev.txt',
        metadata={"help": "An optional input evaluation data file to evaluate on (a csv or JSON file)."},
    )
    test_file: Optional[str] = field(
        default='dataset/cosmetic/test.txt',
        metadata={"help": "An optional input test data file to predict on (a csv or JSON file)."},
    )
    overwrite_cache: bool = field(
        default=False, metadata={"help": "Overwrite the cached training and evaluation sets"}
    )
    preprocessing_num_workers: Optional[int] = field(
        default=None,
        metadata={"help": "The number of processes to use for the preprocessing."},
    )
    pad_to_max_length: bool = field(
        default=False,
        metadata={
            "help": "Whether to pad all samples to model maximum sentence length. "
            "If False, will pad the samples dynamically when batching to the maximum length in the batch. More "
            "efficient on GPU but very bad for TPU."
        },
    )
    max_length: int = field(
        default=64,
        metadata={
            "help": "padding的最大序列长度，默认是64，如果是bert，最长是512"
        },
    )
    label_all_tokens: bool = field(
        default=False,
        metadata={
            "help": "Whether to put the label for one word on all tokens of generated by that word or just on the "
            "one (in which case the other tokens will have a padding index)."
        },
    )

    def __post_init__(self):
        #在parse参数时，会自动检查dataset的后缀或文件 parser.parse_args_into_dataclasses()
        if self.dataset_name is None and self.train_file is None and self.validation_file is None:
            raise ValueError("Need either a dataset name or a training/validation file.")
        else:
            if self.train_file is not None:
                extension = self.train_file.split(".")[-1]
                assert extension in ["csv", "json", "txt"], "`train_file` should be a csv or a json file."
            if self.validation_file is not None:
                extension = self.validation_file.split(".")[-1]
                assert extension in ["csv", "json", "txt"], "`validation_file` should be a csv or a json file."
        self.task_name = self.task_name.lower()


@app.route("/api", methods=['POST'])
def api():
    """
    Args:
        test_data: 需要预测的数据，是一个文字列表
    Returns:

    """
    jsonres = request.get_json()
    test_data = jsonres.get('data',None)
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments))
    model_args, data_args = parser.parse_args_into_dataclasses()
    training_args = TrainingArguments(output_dir="cosmetic_ner",do_predict=True)

    test_dict = {'tokens':[[token for token in line] for line in test_data]}
    datasets = Dataset.from_dict(test_dict)

    text_column_name = "tokens"
    label_list = ['O', 'B-COM', 'I-COM', 'B-EFF', 'I-EFF']

    num_labels = 5

    # 开始加载预训练模型和tokenizer
    # 加载模型配置
    config = AutoConfig.from_pretrained(
        model_args.config_name if model_args.config_name else model_args.model_name_or_path,
        num_labels=num_labels,
        finetuning_task=data_args.task_name,    #ner
        cache_dir=model_args.cache_dir,        #None
    )
    tokenizer = AutoTokenizer.from_pretrained(
        model_args.tokenizer_name if model_args.tokenizer_name else model_args.model_name_or_path,
        cache_dir=model_args.cache_dir,
        use_fast=True,
    )
    model = AutoModelForTokenClassification.from_pretrained(
        model_args.model_name_or_path,
        from_tf=bool(".ckpt" in model_args.model_name_or_path),
        config=config,
        cache_dir=model_args.cache_dir,
    )

    # 数据预处理
    # 最大序列长度
    max_length = data_args.max_length
    # Padding 策略
    padding = "max_length" if data_args.pad_to_max_length else False

    # Tokenize所有文本并将label与它们对齐。
    def tokenize_and_align_labels(examples):
        """
        datasets.map函数处理时会调用
        Args:
            examples: 这里是2条样本,
        例如: examples = {dict: 5}
 'chunk_tags' = {list: 2} [[11, 21, 11, 12, 21, 22, 11, 12, 0], [11, 12]]
 'id' = {list: 2} ['0', '1']
 'ner_tags' = {list: 2} [[3, 0, 7, 0, 0, 0, 7, 0, 0], [1, 2]]
 'pos_tags' = {list: 2} [[22, 42, 16, 21, 35, 37, 16, 21, 7], [22, 22]]
 'tokens' = {list: 2} [['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.'], ['Peter', 'Blackburn']]
        Returns:
        {'input_ids': [[101, 4649, 2244, 102], [101, 6208, 4658, 2094, 3723, 102]], 'token_type_ids': [[0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1], [1, 1, 1, 1, 1, 1]], 'labels': [[-100, 3, 4, -100], [-100, 1, 2, 2, 2, -100]]}
        """
        # 对单条样本的examples的tokens字段，即文本字段进行tokenizer
        tokenized_inputs = tokenizer(
            examples[text_column_name],
            padding=padding,
            max_length=max_length,
            truncation=True,
            # 我们使用此参数是因为数据集中的文本是单词列表(每个单词带有标签)
            is_split_into_words=True,
        )
        print(f"\n样本是{examples}")
        print(f"一个batch的tokenized_inputs,{tokenized_inputs}")
        return tokenized_inputs
    #处理数据，用map函数
    tokenized_datasets = datasets.map(
        tokenize_and_align_labels,
        batched=True,
        num_proc=data_args.preprocessing_num_workers,
        load_from_cache_file=False,
    )

    # Data collator, 在for循环dataloader时调用
    data_collator = DataCollatorForTokenClassification(tokenizer)

    # Initialize our Trainer, msra没有验证集，这里用test测试集，其实应该用train中分离出来
    trainer = Trainer(
        model=model,
        args=training_args,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    #评估模型
    results = {}
    #
    if training_args.do_predict:
        logger.info("*** 预测 ***")
        test_dataset = tokenized_datasets
        predictions = trainer.predict(test_dataset)
        predictions = np.argmax(predictions.predictions, axis=2)

        # 是一个嵌套列表，子列表是label的名字, 去掉prediction的第一个和最后一个元素CLS, SEP
        true_predictions = [
            [label_list[p] for p in prediction[1:-1]]
            for prediction in predictions
        ]
        # 去掉padding的长度
        text_tokens = test_dict['tokens']
        predicts = [prediction[:len(token)] for token, prediction in zip(text_tokens, true_predictions)]
        results = extract_words(text=test_dict['tokens'], predicts=predicts)

    return jsonify(results)


def extract_words(text, predicts):
    """
    Args:
        text: 空格分隔的文本组成的列表
        predicts: 预测标签

    Returns:

    """
    def towords(text, nertag):
        """
        把label或者pridict还原成单词
        返回一个列表，列表中子列表，子列表中包含keywrod
        Args:
            text:
            nertag:

        Returns:
        """
        eff_words = []
        com_words = []
        for line_list, tag_list in zip(text,nertag):
            #每行的功效词和成分词
            line_eff_words = []
            line_com_words = []
            #一个单词，把每个字都加进来，临时存储
            one_words = ""
            for idx, every_tag in enumerate(tag_list):
                #对应的字
                word = line_list[idx]
                if every_tag == "O":
                    if one_words and idx !=0:
                        # 如果是O，并且one_words由内容，需要判断上一个词是什么词，并且判断one_words是什么词，是EFF还是COM类型
                        # idx等于0时肯定不用
                        last_tag = tag_list[idx - 1]
                        if last_tag.endswith("COM"):
                            #说明one_words里面是成分类,否则是成分类，因为我们就2种类别
                            line_com_words.append(one_words)
                        else:
                            line_eff_words.append(one_words)
                        #重置one_words
                        one_words = ""
                #说明2个关键词挨着了，需要把旧词保存
                if every_tag == "B-COM":
                    #把旧的保存
                    if one_words:
                        #把字和功效都加进去
                        line_com_words.append(one_words)
                    #加入新的
                    one_words = word
                if every_tag == "I-COM":
                    one_words += word
                #处理EFF词
                if every_tag == "B-EFF":
                    #把旧的保存
                    if one_words:
                        #把字和功效都加进去
                        line_eff_words.append(one_words)
                    #加入新的
                    one_words = word
                if every_tag == "I-EFF":
                    one_words += word
            #处理最后一个词
            if one_words:
                # 把词加进去， 判断最后一个tag是什么
                last_tag = tag_list[-1]
                if last_tag.endswith("COM"):
                    # 说明one_words里面是成分类,否则是成分类，因为我们就2种类别
                    line_com_words.append(one_words)
                else:
                    line_eff_words.append(one_words)
            #每行的结果，加入列表
            eff_words.append(" ".join(line_eff_words))
            com_words.append(" ".join(line_com_words))
        return eff_words, com_words

    predict_eff_words, predict_com_words = towords(text,predicts)
    print("各个长度")
    print(len(text),len(predicts),len(predict_com_words),len(predict_eff_words))
    result = {'text':text, 'predicts':predicts, '预测标签的功效词':predict_eff_words,'预测标签成分词':predict_com_words}
    return result
if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5001, debug=True, threaded=True)

