# coding=utf-8
import logging
import os
import sys
from dataclasses import dataclass, field
from typing import Optional
from flask import Flask, request, jsonify, abort
import numpy as np
from datasets import ClassLabel, load_dataset
from seqeval.metrics import accuracy_score, f1_score, precision_score, recall_score

import transformers
from transformers import (
    AutoConfig,
    AutoModelForTokenClassification,
    AutoTokenizer,
    DataCollatorForTokenClassification,
    HfArgumentParser,
    PreTrainedTokenizerFast,
    Trainer,
    TrainingArguments,
    set_seed,
)
from transformers.trainer_utils import is_main_process

app = Flask(__name__)
logger = logging.getLogger(__name__)


@dataclass
class ModelArguments:
    """
    Arguments pertaining to which model/config/tokenizer we are going to fine-tune from.
    """

    model_name_or_path: str = field(
        metadata={"help": "Path to pretrained model or model identifier from huggingface.co/models"}
    )
    config_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained config name or path if not the same as model_name"}
    )
    tokenizer_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained tokenizer name or path if not the same as model_name"}
    )
    cache_dir: Optional[str] = field(
        default=None,
        metadata={"help": "Where do you want to store the pretrained models downloaded from huggingface.co"},
    )


@dataclass
class DataTrainingArguments:
    """
    Arguments pertaining to what data we are going to input our model for training and eval.
    """

    task_name: Optional[str] = field(default="ner", metadata={"help": "The name of the task (ner, pos...)."})
    dataset_name: Optional[str] = field(
        default=None, metadata={"help": "The name of the dataset to use (via the datasets library)."}
    )
    script_file: Optional[str] = field(
        default='data/cosmetic_ner.py', metadata={"help": "处理数据集的文件路径"}
    )
    dataset_config_name: Optional[str] = field(
        default='CosmeticsNerConfig', metadata={"help": "The configuration name of the dataset to use (via the datasets library)."}
    )
    train_file: Optional[str] = field(
        default='dataset/cosmetic/train.txt', metadata={"help": "The input training data file (a csv or JSON file)."}
    )
    validation_file: Optional[str] = field(
        default='dataset/cosmetic/dev.txt',
        metadata={"help": "An optional input evaluation data file to evaluate on (a csv or JSON file)."},
    )
    test_file: Optional[str] = field(
        default='dataset/cosmetic/test.txt',
        metadata={"help": "An optional input test data file to predict on (a csv or JSON file)."},
    )
    overwrite_cache: bool = field(
        default=False, metadata={"help": "Overwrite the cached training and evaluation sets"}
    )
    preprocessing_num_workers: Optional[int] = field(
        default=None,
        metadata={"help": "The number of processes to use for the preprocessing."},
    )
    pad_to_max_length: bool = field(
        default=False,
        metadata={
            "help": "Whether to pad all samples to model maximum sentence length. "
            "If False, will pad the samples dynamically when batching to the maximum length in the batch. More "
            "efficient on GPU but very bad for TPU."
        },
    )
    max_length: int = field(
        default=64,
        metadata={
            "help": "padding的最大序列长度，默认是64，如果是bert，最长是512"
        },
    )
    label_all_tokens: bool = field(
        default=False,
        metadata={
            "help": "Whether to put the label for one word on all tokens of generated by that word or just on the "
            "one (in which case the other tokens will have a padding index)."
        },
    )

    def __post_init__(self):
        #在parse参数时，会自动检查dataset的后缀或文件 parser.parse_args_into_dataclasses()
        if self.dataset_name is None and self.train_file is None and self.validation_file is None:
            raise ValueError("Need either a dataset name or a training/validation file.")
        else:
            if self.train_file is not None:
                extension = self.train_file.split(".")[-1]
                assert extension in ["csv", "json", "txt"], "`train_file` should be a csv or a json file."
            if self.validation_file is not None:
                extension = self.validation_file.split(".")[-1]
                assert extension in ["csv", "json", "txt"], "`validation_file` should be a csv or a json file."
        self.task_name = self.task_name.lower()


@app.route("/api", methods=['POST'])
def api():
    """
    Args:
        test_data: 需要预测的数据，是一个文字列表
    Returns:

    """
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, TrainingArguments))
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()

    data_files = {}
    if data_args.train_file is not None:
        data_files["train"] = data_args.train_file
    if data_args.validation_file is not None:
        data_files["validation"] = data_args.validation_file
    if data_args.test_file is not None:
        data_files["test"] = data_args.test_file
    datasets = load_dataset(path=data_args.script_file, name=data_args.dataset_name, data_files=data_files)

    text_column_name = "tokens"

    num_labels = 5

    # 开始加载预训练模型和tokenizer
    # 加载模型配置
    config = AutoConfig.from_pretrained(
        model_args.config_name if model_args.config_name else model_args.model_name_or_path,
        num_labels=num_labels,
        finetuning_task=data_args.task_name,    #ner
        cache_dir=model_args.cache_dir,        #None
    )
    tokenizer = AutoTokenizer.from_pretrained(
        model_args.tokenizer_name if model_args.tokenizer_name else model_args.model_name_or_path,
        cache_dir=model_args.cache_dir,
        use_fast=True,
    )
    model = AutoModelForTokenClassification.from_pretrained(
        model_args.model_name_or_path,
        from_tf=bool(".ckpt" in model_args.model_name_or_path),
        config=config,
        cache_dir=model_args.cache_dir,
    )

    # 数据预处理
    # 最大序列长度
    max_length = data_args.max_length
    # Padding 策略
    padding = "max_length" if data_args.pad_to_max_length else False

    # Tokenize所有文本并将label与它们对齐。
    def tokenize_and_align_labels(examples):
        """
        datasets.map函数处理时会调用
        Args:
            examples: 这里是2条样本,
        例如: examples = {dict: 5}
 'chunk_tags' = {list: 2} [[11, 21, 11, 12, 21, 22, 11, 12, 0], [11, 12]]
 'id' = {list: 2} ['0', '1']
 'ner_tags' = {list: 2} [[3, 0, 7, 0, 0, 0, 7, 0, 0], [1, 2]]
 'pos_tags' = {list: 2} [[22, 42, 16, 21, 35, 37, 16, 21, 7], [22, 22]]
 'tokens' = {list: 2} [['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.'], ['Peter', 'Blackburn']]
        Returns:

        """
        # 对单条样本的examples的tokens字段，即文本字段进行tokenizer
        tokenized_inputs = tokenizer(
            examples[text_column_name],
            padding=padding,
            max_length=max_length,
            truncation=True,
            # 我们使用此参数是因为数据集中的文本是单词列表(每个单词带有标签)
            is_split_into_words=True,
        )
        labels = []
        for i, label in enumerate(examples[label_column_name]):
            # 对每条样本进行处理， label 是列表[3, 0, 7, 0, 0, 0, 7, 0, 0]
            word_ids = tokenized_inputs.word_ids(batch_index=i)
            # word_ids: [None, 0, 1, 2, 3, 4, 5, 6, 7, 8, None]
            previous_word_idx = None
            label_ids = []
            for word_idx in word_ids:
                # 特殊token的单词ID为None的。 我们将label设置为-100，以便在损失函数中自动将其忽略
                if word_idx is None:
                    label_ids.append(-100)
                # 我们为每个单词的第一个token设置label。
                elif word_idx != previous_word_idx:
                    label_ids.append(label_to_id[label[word_idx]])
                # 对于单词中的其他token，我们根据label_all_tokens标志将label设置为当前label或-100。
                # 这里是对token中不是ner的部分，给label，默认给的-100
                else:
                    label_ids.append(label_to_id[label[word_idx]] if data_args.label_all_tokens else -100)
                previous_word_idx = word_idx

            labels.append(label_ids)
        # 最终labels是一个列表
        # {list: 11}[-100, 3, 0, 7, 0, 0, 0, 7, 0, 0, -100]
        # {list: 4}[-100, 1, 2, -100]
        tokenized_inputs["labels"] = labels
        return tokenized_inputs
    #处理数据，用map函数
    tokenized_datasets = datasets.map(
        tokenize_and_align_labels,
        batched=True,
        num_proc=data_args.preprocessing_num_workers,
        load_from_cache_file=False,
    )

    # Data collator, 在for循环dataloader时调用
    data_collator = DataCollatorForTokenClassification(tokenizer)

    # Initialize our Trainer, msra没有验证集，这里用test测试集，其实应该用train中分离出来
    trainer = Trainer(
        model=model,
        args=training_args,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    #评估模型
    results = {}
    #
    if training_args.do_predict:
        logger.info("*** 预测 ***")

        test_dataset = tokenized_datasets["test"]
        predictions, labels, metrics = trainer.predict(test_dataset)
        predictions = np.argmax(predictions, axis=2)

        # Remove ignored index (special tokens)
        true_predictions = [
            [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
            for prediction, label in zip(predictions, labels)
        ]

        output_test_results_file = os.path.join(training_args.output_dir, "test_results.txt")
        if trainer.is_world_process_zero():
            with open(output_test_results_file, "w") as writer:
                for key, value in metrics.items():
                    logger.info(f"  {key} = {value}")
                    writer.write(f"{key} = {value}\n")

        # 保存评估结果
        output_test_predictions_file = os.path.join(training_args.output_dir, "test_predictions.txt")
        if trainer.is_world_process_zero():
            with open(output_test_predictions_file, "w") as writer:
                for prediction in true_predictions:
                    writer.write(" ".join(prediction) + "\n")

    return results


if __name__ == "__main__":
    test_data = ['百亿高活性酵素', 'REPAIRESKIN', '维稳修护', '二裂酵母', '水杨酰植物鞘氨醇', 'BOOSTSKIN', '促进肌肤更新', '木瓜蛋白酶', '轻乙基嗪乙烷磺酸', '*欧莱雅实验室数据', '根据木瓜蛋白酶的添加量和分子量计算得出']
    app.run(host='0.0.0.0', port=6000, debug=True, threaded=True)
    """
    --model_name_or_path cosmetic_ner --dataset_name cosmetic_ner --script_file data/cosmetic_ner.py --train_file dataset/cosmetic/train.txt --validation_file dataset/cosmetic/dev.txt --test_file dataset/cosmetic/test.txt --output_dir cosmetic_ner --do_predict --max_length 64
    """

